### PR TITLE
Fix pagination for pr activity

### PR DESCRIPTION
**Pull request by smacker**

### CODE REVIEW

**Comment by gfleury** [comment]
Hey @smacker, 
Thanks for the PR. Some of the methods are "broken by usability", since there are needed parameters missing. Like the others PR's you opened. 
However, this method, GetPullRequestActivity(projectKey, repositorySlug string, pullRequestID int) works and is probably used on another projects (just checked jenkins-x and it uses). So it's most likely to create another method signature for the new parameter without breaking the old one. 
Let me know your thoughts around this.

**Comment by gfleury** [comment]
https://github.com/jenkins-x/jx/blob/master/pkg/gits/bitbucket_server.go#L515

**Comment by smacker** [comment]
@gfleury Do you think it will be alright if I create `GetPullRequestActivityWithOptions` instead and leave `GetPullRequestActivity` as it is?

**Comment by gfleury** [comment]
> @gfleury Do you think it will be alright if I create `GetPullRequestActivityWithOptions` instead and leave `GetPullRequestActivity` as it is?

@smacker , yapp, I think that is the right thing to do also. Go for it.

**Comment by smacker** [comment]
Updated.

**Comment by gfleury** [comment]
LGTM!
Thanks @smacker !

**Pull request merged**
