### PR TITLE
fix of CreateComment_1

### PR DESCRIPTION
**Pull request by superstas**
Hi there!

I fixed `CreateComment_1` for using [/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/comments
](https://docs.atlassian.com/bitbucket-server/rest/5.15.0/bitbucket-rest.html#idm45622371276656)

Thx!

### CODE REVIEW

**Comment by superstas** [comment]
@gfleury, @sanketjpatel could you please review this change. 
It would help a lot.

Thanks!

**Comment by gfleury** [comment]
Hey man! Thanks a bunch for contributing! I would like to propose one small change.

Follow the same pattern on string replacement for the slugs, as in
https://github.com/gfleury/go-bitbucket-v1/blob/master/default_api.go#L254 

Let me know what you think.

**Comment by superstas** [comment]
@gfleury thanks
PTAL

**Comment by sanketjpatel** [comment]
LGTM! 👍

**Pull request merged**
